### ISSUE TITLE
does not work on wine

### ISSUE THREAD

**Issue by nekoraw** [TheGameratorT/FDLauncher#1]
![Captura de tela de 2022-01-05 21-08-40](https://user-images.githubusercontent.com/50468652/148307578-3f8e1f74-b7e9-40a8-873b-ce1985ac9529.png)

it cannot find the game files even though they are there
doom client works fine through wine

wine version: wine-7.0-rc2 (Staging)
fedora 35

**Comment by TheGameratorT** [comment]
Well, it's shouldn't be too hard to make it natively support Linux instead of using Wine, I could try that.

**Comment by TheGameratorT** [comment]
After a year, I have finally made a Linux port that runs natively, you can get it at:
https://mega.nz/file/v1QkwbKB#fcnk3ilHGQIfDHZgZUMwa4aXpWSG-wM1_egHhih34lc
(you might need to change the chmod permissions for FDLauncher and game/gzdoom)
